### ISSUE TITLE
ボディーの文字数が少ないとき、フッター部分じゃなくボディー部分が伸びた方が気持ちいい気がする

### ISSUE THREAD

**Issue by pnyompen** [alclimb/westa#51]

**Comment by pnyompen** [comment]
![](https://westa.io/resources/image/@pnyompen/01D678CEFN3XTC0KKADNC1G9X6

**Comment by alclimb** [comment]
横着がばれてしまいましたね～
その感覚には同意です。

> ～ ちょっとした裏話 ～
> 見かけ上フッターが伸びているように見えますが、開発者モードで見るとフッターが伸びているのではなくフッターと同じ色の背景色(黒)が表示されているだけだったりします笑

**Comment by alclimb** [comment]
v1.0にて対応済み
