### ISSUE TITLE
公開中の記事を編集した場合、オートセーブで公開中の記事内容も変更されるの？

### ISSUE THREAD

**Issue by pnyompen** [alclimb/westa#52]

**Comment by alclimb** [comment]
## 結論
変更されないよ！

## 詳細
公開中の記事を編集しても下書きバージョンを新しく作るので公開中の内容には影響ありません。
その下書き中の記事を「公開」したタイミングで、公開中の記事内容が切り替わります。
(内部的には記事内容をバージョン管理しています)
