### ISSUE TITLE
ファイルがアップロードされてるのかわかりにくい

### ISSUE THREAD

**Issue by pnyompen** [alclimb/westa#58]
サムネイルに大きめなファイルアップロードしたとき、だいぶ時間が経ってから２M以内にしてくださいの警告がでた。
今アップロードされている最中なのかわからず、2回アップロード処理をしてしまった。

こんな感じのあるとわかりやすい気がしました
https://github.com/pqina/filepond

**Comment by alclimb** [comment]
- アップロード前にファイルサイズのチェックを追加
- アップロード中に処理中アニメーションを追加
