### ISSUE TITLE
キャッシュされているはずなのにサムネイルの表示が遅い

### ISSUE THREAD

**Issue by pnyompen** [alclimb/westa#60]

**Comment by alclimb** [comment]
## 状況
- 画像リソースに関しては一時リダイレクト(302)を使用していたのでその影響かも
- それと vuetify の v-img コンポーネントの画像遅延ロード(lazy-src)を SSR で使うと SPA が完全ロードされるまでグルグルする模様
- そもそもサムネイルのファイルサイズが大きい

## 対応済み
- リダイレクトせずに直接画像リソースにアクセスするように変更
- サムネイルのファイルサイズ縮小化機能を実装済み
