### ISSUE TITLE
いいねボタンがない

### ISSUE THREAD

**Issue by pnyompen** [alclimb/westa#63]

**Comment by alclimb** [comment]
### メモ
現状、記事閲覧画面でPC画面サイズだと画面左側に表示されるが、タブレットとスマホの画面サイズだと表示されていない。

### 対応
⇒ タブレットとスマホの画面サイズの場合でも、邪魔にならない場所を検討して表示させます～

**Comment by alclimb** [comment]
とりあえず記事下に評価関係のボタンを追加
